global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'quickbite-backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'api-gateway:8080'
          - 'quickbite-user:8081'
          - 'quickbite-restaurant:8082'
          - 'quickbite-order:8083'
          # - 'quickbite-notification:8084'
  
  - job_name: 'vps-hardware'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['node-exporter:9100']