services:
  action-runner:
    image: myoung34/github-runner:latest
    container_name: action-runner
    restart: always
    environment:
      RUNNER_SCOPE: "org"
      ORG_NAME: "backend-fullskill-devops"
      RUNNER_NAME: "quickbite-selfhosted-runner-01"
      RUNNER_TOKEN: ${RUNNER_TOKEN}
      RUNNER_LABELS: "self-hosted,quickbite,backend,ubuntu"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - action-runner-work:/data/_work

volumes:
  action-runner-work:
